### PR TITLE
Updated the extract_reduced_accuracy_lat_long function to accept an o…

### PR DESCRIPTION
**Pull request by fritzbrand**
…ption 'resolution' argument, so we can change the number of decimal points returned

### CODE REVIEW

**Comment by jerith** [comment]
Would it make sense to add some tests for which the the result is different depending on the `resolution` value?

**Comment by erikh360** [comment]
Looks good to me. 👍🍰

**Comment by fritzbrand** [comment]
@jerith I have updated the tests, please check

**Comment by jerith** [comment]
The choice of test data (`±40.20361` for both lat and long) has two consequences for the tests:

1. `utils.extract_reduced_accuracy_lat_long(x, 1)` is equal to `utils.extract_reduced_accuracy_lat_long(x, 2)` in all the assertions, which means we're not actually testing that the new `resolution` arg changes the behaviour. To demonstrate this, change the second parameter in the `round()` calls (lines 94 and 95 in `utils.py`) back to `1` and rerun the tests.
2. Using the same magnitude (even with different signs) for both lat and long makes it harder to visually distinguish between them. This could potentially hide a bug that swaps lat and long, if the tests also have them swapped.

The quick fix for both of these is to change the test data. Perhaps `±40.21361` for lat and `±35.16361` for long, although any values that don't have those properties are fine.

More generally, I find it useful to add or update tests to match the desired behaviour before touching the non-test code. That way I can be sure that the new behaviour is actually being tested, because the tests fail for the old behaviour. It's also a good way to explore the existing behaviour of code that I may not be familiar with. 😄

**Review by jerith — APPROVED** [review]
:+1:

**Pull request merged**
